# Generated by Django 6.0.8 on 2026-08-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="banners/")),
                ("display_order", models.IntegerField(default=1)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="initiatives/")),
                ("display_order", models.IntegerField(default=1)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=50)),
                ("display_order", models.IntegerField(default=1)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="VisionMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vision_title", models.CharField(max_length=150)),
                ("vision_description", models.TextField()),
                ("mission_title", models.CharField(max_length=150)),
                ("mission_description", models.TextField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
